### PR TITLE
Adds Zelda3 port

### PR DESCRIPTION
**Pull request by tailtwo**
Adds Zelda3 port. Requires `zelda3_assets.dat` file to work.

Sources : https://github.com/tailtwo/zelda3/tree/miyoo
SDL sources : https://github.com/tailtwo/sdl2_miyoo/tree/zelda3

### CODE REVIEW

**Comment by XK9274** [comment]
Hey! 

Thanks for the new ports ❤️

If this requires extra data files can you drop a file in called `_required_files.txt` containing a tree of how the directory should look as this will allow the README to be built with the github actions

[Similar to this one](https://github.com/OnionUI/Ports-Collection/blob/main/Sonic%20Mania/Roms/PORTS/Games/Sonic%20Mania/_required_files.txt)

**Comment by tailtwo** [comment]
Sure, is there a way to generate it or does it have to be created by hand? `tree` Linux command doesn't use the same syntax.

**Review by XK9274 — CHANGES_REQUESTED** [review]
@tailtwo For Windows users can you remove the `:` from the filename please?

Have also messaged you on discord re: this - can't get it running with my data files. 

```
:: RUNNING THE PORT
--------------------------------------------------------------------
running Zelda 3 (Port) ...
Command line :
/mnt/SDCARD/Roms/PORTS/Games/zelda3/zelda3


MMIYOO_CreateWindow, w:0, h:0
That operation is not supported
MMIYOO_OpenDevice, freq:44100 sample:512 channels:2
 _MI_AO_OpenVqeLib: success
 _MI_AO_OpenSrcLib: success
 _MI_AO_OpenG711Lib: success
 _MI_AO_OpenG726Lib: success
Bus error (core dumped)
````

Maybe I have the wrong files - will come back to this later.

**Comment by tailtwo** [comment]
Folder renamed, feel free to contact me on Discord at any time.

**Review by XK9274 — APPROVED** [review]
Engine only:

```
Current file ---- : /mnt/SDCARD/Emu/PORTS/../../Roms/PORTS/Shortcuts/Action/zelda3.port
GameDir --------- : /mnt/SDCARD/Roms/PORTS/Games/zelda3
GameDataFile ---- : zelda3_assets.dat
/mnt/SDCARD/Roms/PORTS/Games/zelda3/zelda3_assets.dat
Presence -------- :  OK
```

Imports fine when zelda3_assets.dat present. Played just past naming screen only. 

Thanks!

**Pull request merged**
