### PR TITLE
Adds Prince of Persia port

### PR DESCRIPTION
**Pull request by JulienChebance**
Adds Prince of Persia to port collection.

Based on [SDLPoP](https://github.com/NagyD/SDLPoP), with [SDL2 port to Miyoo](https://github.com/XK9274/sdl2_miyoo).

_Controls:_
D-Pad: arrows
A: Show how much time is left
Y: Shift
Central button: Display in-game menu

**Only tested on Miyoo Mini Plus.**

### CODE REVIEW

**Comment by XK9274** [comment]
Hey there,

Thanks for the new port ❤️ I see you used my fork of [Steward-Fu'](https://github.com/steward-fu/sdl2)s SDL2 libraries, did you run into any issues? 

Can also see this adds a lot of data files but it's mostly [under GPLv3](https://github.com/NagyD/SDLPoP/blob/master/src/GPLv3.h) - can you confirm that 100% of the files you're PR'ing are honouring the licenses, if so i'll test and we'll move to merge. 

If this is a full port containing the engine and the data files and licenses are honoured, then no other actions should be needed other than testing 👍

**Comment by JulienChebance** [comment]
Hi,

Kind of... Actually, I finally took the libs from the Sonic Mania port of @tailtwo :-o
However, thank you for your warning about TARGET vs STREAMING, as the default configuration of SDLPoP uses TARGET textures.

About licenses, I confirm I did modify nothing except the configuration file (SDLPoP.ini). I also let the /src and /doc folders as is. So, even if I'm not a GPL expert, I think that's ok to redistribute these files.

It's a full port.

**Comment by tailtwo** [comment]
FYI the Miyoo SDL2 lib uses linear scaling by default to scale video output. In case you want nearest scaling for crisp pixels, you can use this commit from my repo : https://github.com/tailtwo/sdl2_miyoo/commit/12440cb19314d9fb6fac8bd0b545719aa0aba202
Depending on your initial resolution, you may want to tweak numerical values. This example is for 320x240 to 640x480.
If someone could figure out how to use this tweak to implement `SDL_HINT_RENDER_SCALE_QUALITY`, that would be amazing!

**Comment by XK9274** [comment]
@JulienChebance is @tailtwo's suggestion something you wanted to implement or are you happy the way things are?

**Comment by JulienChebance** [comment]
> @JulienChebance is @tailtwo's suggestion something you wanted to implement or are you happy the way things are?

I won't have time to check tailtwo proposition, so the current version is fine for me.

**Review by XK9274 — APPROVED** [review]
Thanks for the port :) Imports and plays fine. 

```
Current file ---- : /mnt/SDCARD/Emu/PORTS/../../Roms/PORTS/Shortcuts/Platform/Prince of Persia.notfound
GameDir --------- : /mnt/SDCARD/Roms/PORTS/Games/Prince of Persia
GameDataFile ---- : prince
/mnt/SDCARD/Roms/PORTS/Games/Prince of Persia/prince
Presence -------- :  OK
```

**Pull request merged**
